apiVersion: v1
kind: Pod
metadata:
  name: my-secret-pod
  labels:
    app: my-app
spec:
  containers:
  - name: my-container
    image: my-image:latest
    ports:
    - containerPort: 80
    env:
    - name: MY_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: secret-key
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  secret-key: c2VjcmV0dmFsdWU= # base64 encoded value
