apiVersion: v1
kind: Pod
metadata:
  name: my-multicontainer-pod
  labels:
    app: my-app
spec:
  containers:
  - name: container-1
    image: image-1:latest
    ports:
    - containerPort: 80
  - name: container-2
    image: image-2:latest
    ports:
    - containerPort: 8080
