apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
spec:
  containers:
  - name: my-container
    image: my-image:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: my-volume
      mountPath: /mnt/my-data
  volumes:
  - name: my-volume
    emptyDir: {}
